// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GmusicbrowserRemote
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gmusicbrowser = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int media_next = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int media_pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int media_play = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int media_previous = 2130837509;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int ArtistTextView = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int NextButton = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int PlayButton = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int PrevButton = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int RatingBar = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int SongSeekbar = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int TitleTextView = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int VolumeSeekBar = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout3 = 2131034119;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int connection_progress = 2130968577;
			
			private String()
			{
			}
		}
	}
}
